# Generated by Django 3.0.3 on 2020-03-06 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=56, verbose_name='Product Name')),
                ('product_image', models.ImageField(upload_to='Products_Image', verbose_name='Image')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Discount Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
