# Generated by Django 3.0.3 on 2020-03-14 09:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.FloatField()),
                ('objectid', models.FloatField()),
                ('code_id', models.FloatField()),
                ('name', models.CharField(max_length=70)),
                ('code', models.CharField(max_length=3)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.DeleteModel(
            name='MySupplier',
        ),
    ]
