# Generated by Django 3.0.3 on 2020-03-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('Beauty & Cosmetics', 'Beauty & Cosmetics'), ('Electronics', 'Electronics')], max_length=30, unique=True),
        ),
    ]
