# Generated by Django 3.0.3 on 2020-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200305_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Supplier_Profile_picts'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='telephone',
            field=models.CharField(default='+254', max_length=20),
        ),
    ]
