# Generated by Django 3.0.3 on 2020-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200305_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Customer_profile_picts'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
